import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
  normal = { family = "MesloLGM Nerd Font", style = "Regular" }
  size = 12
[window]
  opacity = 0.80
  decorations_theme_variant = "Dark"
  blur = true 
