import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
  normal = { family = "MesloLGM Nerd Font", style = "Regular" }
  size = 12
[window]
  opacity = 0.90
  decorations_theme_variant = "Dark"
  # decorations = "Transparent"
  decorations = "Buttonless"
  blur = true 
  padding = { x = 5, y = 5 }
  dynamic_padding = true
[keyboard]
  bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left",  mods = "Alt", chars = "\u001BB" },
  ]
