#!/bin/bash

# Colors
white='0xffe1e3e4'
black='0xff494d64'
red="0xfff7768e"
blue="0xff7aa2f7"

red72="0xfff7768e"
red35="0xffa90a27"

blue72="0xff7aa2f7"
blue35="0xff0a3ca9"

redGradient="gradient(top_left=$red72,bottom_right=$red35)"
blueGradient="gradient(top_left=$blue72,bottom_right=$blue35)"


options=(
	style=round
	width=6.0
	hidpi=on
	active_color="$redGradient"
	inactive_color="$blueGradient"
)

borders "${options[@]}"