console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  blue = '#89B4FA'
  closer = 'p:os'
  lavender = '#B4BEFE'
  os = '#ACB0BE'
  pink = '#F5C2E7'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:blue'
  background = 'transparent'

[transient_prompt]
  template = '󰜎 ❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}p:pink{{end}}', '{{if eq .Code 0}}p:blue{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{.Icon}} '
    foreground = 'p:os'
    type = 'os'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ if .SSHSession }} {{ end }} '
    foreground = 'p:os'
    type = 'session'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = '....'
      home_icon = '~'
      max_depth = 2
      style = 'agnoster_short'

  [[blocks.segments]]
    foreground = 'p:lavender'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = ' {{.Profile}}{{if .Region}}@{{.Region}}{{end}} '
    foreground = 'p:lavender'
    type = 'aws'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = 'ﴱ {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} '
    foreground = 'p:lavender'
    type = 'kubectl'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' '
    foreground = 'p:lavender'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  '
    foreground = 'p:lavender'
    type = 'npm'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' '
    foreground = 'p:lavender'
    type = 'php'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

  [[blocks.segments]]
    template = ' {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }} '
    type = 'battery'
    style = 'plain'
    foreground_templates = ['{{if eq "Charging" .State.String}}#40c4ff{{end}}', '{{if eq "Discharging" .State.String}}#ff5722{{end}}', '{{if eq "Full" .State.String}}#4caf50{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
      charged_icon = ' '
      charging_icon = ' '
      discharging_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '󰜎 ❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}p:pink{{end}}', '{{if eq .Code 0}}p:blue{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
